version: '3.7'
services:
  jenkins:
    image: rhdp/jenkins:latest
    build:
      context: jenkins/
    ports:
      - "8080:8080"

  # sonarqube:
  #   links:
  #     - mysql
  #   image: sonarqube:6.7.5
  #   environment:
  #     - SONARQUBE_JDBC_USERNAME=sonar
  #     - SONARQUBE_JDBC_PASSWORD=sonar
  #     - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&useSSL=false
  #   ports:
  #     - 9000:9000
  #
  # mysql:
  #   image: rhdp/mysql
  #   build:
  #     context: mysql/
  #   environment:
  #     - MYSQL_USERNAME=sonar
  #     - MYSQL_PASSWORD=sonar
  #     - MYSQL_DATABASE=sonar
  #     - MYSQL_ROOT_PASSWORD=sonar
  #   hostname: mysql
  #   expose:
  #     - 3306

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:6.4.2
  #   volumes:
  #     - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
  #   ports:
  #     - 5601:5601

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - 3000:3000
